### ISSUE TITLE
sfdx-lwc-jest: command not found

### ISSUE THREAD

**Issue by jflowers45** [salesforce/sfdx-lwc-jest#102]
### Description
Prior to WN'20 I was using lwc-jest (not sfdx-lwc-jest) and had no problems running jest tests against my LWC project. However, on a project with sfdx-project.json sourceApiVersion 47.0 I'm trying to follow the instructions here:
https://developer.salesforce.com/docs/component-library/documentation/lwc/lwc.unit_testing_using_jest_installation
When I get to the part that asks me to do an 
**npm run test:unit**
it's giving me an error
_sfdx-lwc-jest: command not found_

In case it helps, I noticed that running
**npm install @salesforce/sfdx-lwc-jest --save-dev**
creates an lwc-jest alias in node_modules/.bin/, but no alias is created for sfdx-lwc-jest

In order to run tests, I have to change the sourceApiVersion of my project back to 46.0 and I also have to change my package json entry for test:unit:watch to use lwc-jest instead of sfdx-lwc-jest

#### Steps to Reproduce
```bash
npm install @salesforce/sfdx-lwc-jest --save-dev
```

Then edit package.json
```.json
"scripts": {
    ...
    "test:unit": "sfdx-lwc-jest",
    "test:unit:watch": "sfdx-lwc-jest --watch",
    "test:unit:debug": "sfdx-lwc-jest --debug",
    ...
  },
```
then run
```bash
npm run test:unit
```
#### Expected Results
jest tests run
#### Actual Results
terminal reports that sfdx-lwc-jest: command not found

### Version
- @salesforce/sfdx-lwc-jest: 0.5.5
- Node: v10.16.3

**Comment by tgentet-obrien** [comment]
Do we have an ETA on this? It's effecting a few of my projects I have on at the moment :(

**Comment by dquijada** [comment]
I'm getting the same error. Is there a work around for this?

**Comment by muenzpraeger** [comment]
The command is still `lwc-test`.

**Comment by jflowers45** [comment]
@muenzpraeger are you saying the command isn't going to change, or that it just hasn't changed yet?
