### ISSUE TITLE
Found 4 vulnerabilities (2 moderate, 2 high)

### ISSUE THREAD

**Issue by chendagit** [salesforce/sfdx-lwc-jest#104]
Repro:
Run `npm install` with this package.json
```json
"devDependencies": {
    "@salesforce/sfdx-lwc-jest": "^0.5.4"
  }
```

**Comment by muenzpraeger** [comment]
Does this occur with the latest version too?

**Comment by chendagit** [comment]
@muenzpraeger 
Yes.
Also in alpha 2:  Found 2 vulnerabilities (1 moderate, 1 high)

**Comment by pmdartus** [comment]
This is a known issue with some of the LWC compiler dependencies https://github.com/salesforce/lwc/issues/1331.
