### ISSUE TITLE
Versions are not aligned in repo/npm/docs

### ISSUE THREAD

**Issue by pozil** [salesforce/sfdx-lwc-jest#105]
Project versions are not aligned across repository, npm and docs. Here's what we currently see for latest release:
- GitHub releases: 0.5.5
- GitHub changelog: 0.5.3
- npm: 0.6.1

Please align them.

**Comment by Gr8Gatsby** [comment]
@trevor-bliss how can we fix this difference? I noticed this as well when someone posted their current version was 0.6.1 and master only goes up to 0.5.5

**Comment by trevor-bliss** [comment]
@Gr8Gatsby it's not difficult but it's a manual process still. 0.6.1 is the latest version so everything should match up to that. 

For the GitHub release the git tags that match the release commits need to be pushed. Or you can manually publish new releases via the Releases tab of the repo.

For the changelog, that file needs to be manually edited with the changes for each release and pushed via a PR. 

The npm version of 0.6.1 is correct for sfdx-lwc-jest and lwc-jest.

**Comment by trevor-bliss** [comment]
Everything points to 0.7.0 on master now.
