### ISSUE TITLE
Unknown public property "required" of element <lightning-input-field>.

### ISSUE THREAD

**Issue by jduelfer** [salesforce/sfdx-lwc-jest#106]
### Description

After the Winter '20 release, I added the newly supported `required` attribute to `<lightning-input-field>` elements in my Lightning Web Components. On running tests, I get the following error:

`Unknown public property "required" of element <lightning-input-field>. This is likely a typo on the corresponding attribute "required".`

#### Steps to Reproduce

```js
it ('Shows form', () => {
    const element = createElement('c-component', {is: MyComponent});
    element.showForm = true;
    document.body.appendChild(element);

    return Promise.resolve().then(() => {
        // doesn't arrive here, as error is thrown on appending element to the document   
    });
});
```

```html
<!-- HTML for component under test -->
<template if:true={showForm}>
    <lightning-record-edit-form record-id={myId}>
        <lightning-input-field field-name="FieldName" required></lightning-input-field>
    </lightning-record-edit-form>
</template>
```

```js
// JS for component under test
import { LightningElement } from 'lwc';

export default class Foo extends LightningElement {
    @api myId;
    @api showForm = false;
}
```

```bash
# Command to repro
lwc-jest -- --no-cache
```

#### Expected Results
The test does not fail, as the `required` attribute is supported in metadata api version 47.0.

#### Actual Results
The test fails due to `required` not being supported with the following message: 

`Unknown public property "required" of element <lightning-input-field>. This is likely a typo on the corresponding attribute "required".`

### Version
- @salesforce/sfdx-lwc-jest: 0.6.1
- Node: 12.10.0

**Possible Solution**
N/A

**Additional context/Screenshots**
N/A

**Comment by pmdartus** [comment]
Fixed with #114.
