### ISSUE TITLE
Add prettier for code formatting

### ISSUE THREAD

**Issue by pmdartus** [salesforce/sfdx-lwc-jest#116]
### Description

Currently there is no code formatting tool integrated with this repository. In order to ensure consistent code style, it would be great to add prettier to the repository and run it: 
* on the local dev machine: using a pre-commit hook
* on the CI: to enforce code styling

**Comment by trevor-bliss** [comment]
Anxiously awaiting your PR @pmdartus :)

**Comment by pmdartus** [comment]
I am now anxiously waiting for the PR to be reviewed :laughing:
