### ISSUE TITLE
Add Ability to Specify Max Workers

### ISSUE THREAD

**Issue by NathanWenslaff** [salesforce/sfdx-lwc-jest#122]
### Description
`lwc-jest` uses too much memory in CircleCI. Normally you can get around this by reducing the maximum number of workers. (Using the `--maxWorkers` flag in Jest)

#### Steps to Reproduce
There isn't an easy way to reproduce this, but a project that has a large number of jest unit tests will fail in CircleCi with the error `ENOMEM: not enough memory, read`

#### Expected Results
I have the ability to specify the maximum number of workers.

#### Actual Results
I cannot specify the maximum number of workers.

### Version
CircleCI is configured to use the latest version of node.

**Comment by tmatthews092** [comment]
@NathanWenslaff  what was the resolution of this ticket? Were you able to figure out how to get around this?

**Comment by vnehess** [comment]
We are observing this error with only 38 LWC jest tests.   Today we have >500 apex tests and expect to be able to run 300+ jest tests as we build for production.  This issue will prevent us from using circle-ci with lwc-jest, thanks for any insight on a path forward.

**Comment by muenzpraeger** [comment]
You can pass in any Jest param via passthrough, as documented in the README.

Also for CircleCI you may want to consider this:

`npm run test:unit:coverage -- -- --runInBand`

**Comment by tmatthews092** [comment]
@muenzpraeger Thanks for the advice. We'll move forward with this to see if it fixes the issue.

**Comment by vnehess** [comment]
@muenzpraeger, thanks!
