### ISSUE TITLE
Map Releases to sourceApiVersion?

### ISSUE THREAD

**Issue by tsneed290** [salesforce/sfdx-lwc-jest#123]
### Description
This is just a documentation enhancement request. I have a project who's current sourceApiVersion is 46.0 I installed this latest package (0.6.2) and was met with the common error "expected <version> but got <oldVersion>". After some digging I found that 0.5.5 is what works with 46.0 sourceApiVersion. Would be nice to map this library's releases with the corresponding expecting sourceApiVersion, possibly in the CHANGELOG?

Thanks!
Tim

#### Steps to Reproduce
None

**Comment by pmdartus** [comment]
We can definitely add this to the `CHANGELOG.md`. @trevor-bliss What do you think about also tagging the version on NPM, the same way we do on LWC?

**Comment by trevor-bliss** [comment]
I don't mind using npm dist-tags to map previous releases to appropriate versions of this package.

We could also improve the error message thrown to help guide users to fixing the issue. Maybe pointing them to a section in the README that explains what's going on.

**Comment by dominic-butlerSFDC** [comment]
I've run into this same issue just now. My project sourceApiVersion is 47.0 I've just installed this package and when I run it I get:

`Invalid sourceApiVersion found in sfdx-project.json. Expected 49.0, found 47.0`

I can understand the prerelease thing where if you are developing on a prerelease version of Salesforce that you have to use a special branch because you are on the cutting edge. But I don't understand why I need to comb through old versions of this package to try find one that works with my project's sourceApiVersion.

I'm just starting out with Jest and testing in general so maybe there is something obvious I'm missing here but I really don't understand this at all. The way I would expect it to work would be for each new version to provide support for all previous versions rather than just the new version - that's how code libraries normally work isn't it?

**Comment by ravijayaramappa** [comment]
@dominic-butlerSFDC the outgoing release `@salesforce/sfdx-lwc-jest@0.7.1` has been tagged as `spring20` and `@salesforce/sfdx-lwc-jest@0.6.2` as `winter20`. The `latest` tag of sfdx-lwc-jest will always track with the current release of salesforce in production. If you wish to use version 47.0, please choose `winter20` as the dependency version in package.json.

**Comment by dominic-butlerSFDC** [comment]
@ravijayaramappa thank-you for your response. I'm sorry but I think you need to spell this out a bit more clearly for me (and, I imagine, others). How, exactly do I 'choose winter20 as the dependency version in package.json'?

I've had a look through all the tags on this repo (which don't seem to provide any useful information that I can find - they don't mention which api version they are aligned with), I've read the README which doesn't explain how to do this. How do I do this? If you explain I will write it up and add a PR. I doubt I'll be the only one who is confused by this. Thanks.

**Comment by dominic-butlerSFDC** [comment]
OK. I've found it on the npm site here:

https://www.npmjs.com/package/@salesforce/sfdx-lwc-jest under the Versions tab.

Is it possible to have this in the repo somewhere?

**Comment by BatemanVO** [comment]
@pmdartus @trevor-bliss I'm actually having trouble finding said mapping that @dominic-butlerSFDC mentioned, I agree it would be nice to be in the repo somewhere.

Our SF instance also just upgraded to API v50, but specifying `sourceApiVersion` of 50 causes the latest version of this package to fail with an expected instance of 49. It's causing all of our devs to have to create components, then manually go edit the XML file to update it to 50.

Do we have a timeline on when this package will be up to date to work with the latest SF release?

**Comment by kevinv11n** [comment]
Here's the click path to what @dominic-butlerSFDC  outlined:

<img width="1029" alt="Screen Shot 2020-10-15 at 1 24 24 PM" src="https://user-images.githubusercontent.com/1381403/96182217-042b1300-0eea-11eb-933a-ed4f4a44e033.png">

**Comment by kevinv11n** [comment]
There are sfdx plugins that can simplify bulk changes to API versions. See https://github.com/muenzpraeger/sfdx-plugin#sfdx-mzprsourceapiset.  @mshanemc maintains an index of great sfdx plugins at https://github.com/mshanemc/awesome-sfdx-plugins.

**Comment by tonyward-auden** [comment]
> @pmdartus @trevor-bliss I'm actually having trouble finding said mapping that @dominic-butlerSFDC mentioned, I agree it would be nice to be in the repo somewhere.
> 
> Our SF instance also just upgraded to API v50, but specifying `sourceApiVersion` of 50 causes the latest version of this package to fail with an expected instance of 49. It's causing all of our devs to have to create components, then manually go edit the XML file to update it to 50.
> 
> Do we have a timeline on when this package will be up to date to work with the latest SF release?

Am having the same issue. 

Is there another way to install prerelease into a Salesforce project? e.g. sfdx force:lightning:lwc:test:setup --prerelease

Or do we have to wait for it to be published?

**Comment by BatemanVO** [comment]
Our Org is now on API v51, but installing `sfdx-lwc-jest` version 0.11.0, which, [from the versions tab on the NPM website](https://www.npmjs.com/package/@salesforce/sfdx-lwc-jest), is the latest version, I receive the error:

```error Invalid sourceApiVersion found in sfdx-project.json. Expected 50.0, found 51.0```

@trevor-bliss @pmdartus Is there a release schedule or any documentation we can reference for expected release dates to know when we can update our `sfdx-lwc-jest` packages to match current Org API versions?

**Comment by mugshepherd** [comment]
Having the same issue.  The current setup mapping against names but not the expect/found version numbers - or having a way to align those - is confusing.
