### ISSUE TITLE
Support test result output in TAP format for CI servers such as Jenkins to consume

### ISSUE THREAD

**Issue by KeithClarke** [salesforce/sfdx-lwc-jest#128]
The simple TAP format (https://en.wikipedia.org/wiki/Test_Anything_Protocol) is supported by Continuous Integration (CI) servers such as Jenkins. Adding support for TAP here, would allow the LWC test output to be merged and presented with other test output such as Apex tests results in the overall build output, with no more effort than redirecting the output to a file.

Or perhaps there is already a way to configure TAP output?

**Comment by muenzpraeger** [comment]
As it‘s all based on Jest you can use an addon like [this](https://github.com/MailOnline/jest-tap-reporter).

**Comment by KeithClarke** [comment]
Kinda painful to setup and the configuration for TAP vs JUnit is very different. But all sorted now - see https://salesforce.stackexchange.com/questions/294736/does-sfdx-lwc-jest-support-the-tap-or-junit-test-result-format-that-ci-servers-c.
