### ISSUE TITLE
Invalid sourceApiVersion found in sfdx-project.json. Expected 47.0, found 48.0 error

### ISSUE THREAD

**Issue by anmolgkv** [salesforce/sfdx-lwc-jest#133]
### Description
Getting error when running jest with an sfdx project at version 48

#### Steps to Reproduce
My SFDX project is at API version 48
sfdx-project.json
```
{
  "packageDirectories": [
    {
      "path": "force-app",
      "default": true
    }
  ],
  "namespace": "",
  "sfdcLoginUrl": "https://login.salesforce.com",
  "sourceApiVersion": "48.0"
}
```

```js
// simplified test case
import { createElement } from "lwc";

import Modal from "c/modal";


describe("c-test-jest initialize", () => {
    it("message should be initialization", () => {
        // Setup
        const modal = initElement();


        // Exercise
        return Promise.resolve().then(() => {


            // Verify
            expect(modal.shadowRoot.querySelector(".message")).not.toBeNull();
        });
    });

    // HELPER

    function initElement() {
        let element = createElement("c-modal", {
            is: Modal
        });

        document.body.appendChild(element);
        return element;
    }
});
```

```html
<!-- HTML for component under test -->
<template>
    <div class="message">Hello World!</div>
</template>
```

```js
import { LightningElement } from 'lwc';

export default class Modal extends LightningElement {}
```

```js


```bash
# Command to repro
lwc-jest -- --no-cache
```

#### Expected Results

Jest test should run and pass
#### Actual Results
 Invalid sourceApiVersion found in sfdx-project.json. Expected 47.0, found 48.0 error when running jest tests

### Version
- @salesforce/sfdx-lwc-jest: "^0.7.0"
- Node: v12.13.1

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/8535288/75676254-e25c8300-5cae-11ea-8f0f-b484eb952c5c.png)

**Comment by pozil** [comment]
@anmolgkv can you try to reinstall your Node dependencies?
Run `npm install` or `yarn install` depending on your package manager.

**Comment by trevor-bliss** [comment]
Yes, as @pozil said, looks like you just need to be on version 0.7.0 of this package, which expects API version 48.0.

**Comment by anmolgkv** [comment]
I was already using version 0.7.0, turns out it was cache issue after running `npm cache clean --force` and` npm install `the problem was resolved

**Comment by renatoliveira** [comment]
For future reference, if you leave the default version on the file (the one that the CLI creates for you) then it might be outdated when you run te test suites.

You can update the package like @anmolgkv said. The command is basically the same for Yarn as well.

On CI/CD systems, however, I strongly recommend updating the version on the package.json file, as the executor might redownload the files on every run. I had to update the line within the `devDependencies` in my project to `^0.10.4`, for example.

To update locally (so the version is updated on the file as well) you can use `yarn update @salesforce/sfdx-lwc-jest@latest`.
