### ISSUE TITLE
Synthetic Shadow not properly loaded

### ISSUE THREAD

**Issue by trevor-bliss** [salesforce/sfdx-lwc-jest#139]
### Description

This project has it's own Jest [config](https://github.com/salesforce/sfdx-lwc-jest/blob/master/src/config.js#L21-L35) defined, which only defers to `@lwc/jest-preset` for certain things like the `testEnvironment` entry. `@lwc/jest-preset` now also has a [`setupFilesAfterEnv` entry](https://github.com/salesforce/lwc-test/blob/master/packages/%40lwc/jest-preset/jest-preset.js#L19) that sets up the Synthetic Shadow. This setup script is not included here.

#### Steps to Reproduce

Can provide a sample repo if necessary.

### Version

-   @salesforce/sfdx-lwc-jest: 0.7.1
-   Node: 12.14.1

**Possible Solution**

The simple fix is to add `setupFilesAfterEnv: jestPreset.setupFilesAfterEnv,` to config.js. However, it might be better to think about a more generic way to consume new entries and updates to `@lwc/jest-preset`.

**Comment by pmdartus** [comment]
This has been fixed with: https://github.com/salesforce/sfdx-lwc-jest/pull/177
