### ISSUE TITLE
Unexpected behavior when importing component in jest

### ISSUE THREAD

**Issue by anmolgkv** [salesforce/sfdx-lwc-jest#140]
### Description
When I am importing a module in LWC jest with an upper case character, It runs successfully in my local environment but fails when I run the same test through a bitbucket pipeline.
#### Steps to Reproduce

- Simplified test case (sample.test.js)
```js
import { createElement } from 'lwc';
//Note: I am importing c/Sample with upper case
import Sample from 'c/Sample';

describe('c-sample', () => {
    afterEach(() => {
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('displays greeting', () => {
        // Create element
        const element = createElement('c-sample', {
            is: Sample
        });
        document.body.appendChild(element);

        // Verify displayed greeting
        const header = element.shadowRoot.querySelector('h1');
        expect(header.textContent).toBe('Hello, World!');
    });
});
```

- Simplified HTML (sample.html)
```html
<template>
    <h1>Hello, World!</h1>
</template>
```

- Simplified JS (sample.js)
```js
// JS for component under test
import { LightningElement } from 'lwc';

export default class Sample extends LightningElement {
    ...
}
```

```bash
# Command to repro
npm run test:unit sample
```
Package.json

```js
{
    "name": "sample",
    "version": "1.0.0",
    "devDependencies": {
        "@salesforce/sfdx-lwc-jest": "^0.7.0"
    },
    "scripts": {
      "test:unit": "sfdx-lwc-jest",
      "test:unit:watch": "lwc-jest --watch",
      "test:unit:debug": "lwc-jest --debug"
    },
    "author": "",
    "license": "ISC"
  }
```

#### Expected Results

The test should fail with the message  **Can not find module 'c/Sample' from 'sample.test.js'**

#### Actual Results

The test passes in my local environment but fails when I run the same script from the Bitbucket pipeline.(Error message:  **Can not find module 'c/Sample' from 'sample.test.js'**)

### Version

-   @salesforce/sfdx-lwc-jest: 0.7.0
-   Node: 12.16.1

**Comment by pmdartus** [comment]
This is due to the fact your local environment is case insensitive while the CI environment is. When it comes to node developments, a rule on the thumb is to always consider the environment case sensitive.
