### ISSUE TITLE
export ShowToastEventName = 'lightning__showtoast';

### ISSUE THREAD

**Issue by CarlosIribar** [salesforce/sfdx-lwc-jest#142]
### Description
The const showToastEventName is not exported and when someone follow a test receipt like this [one](https://github.com/trailheadapps/lwc-recipes/blob/master/force-app/main/default/lwc/miscNotification/__tests__/miscNotification.test.js) the ShowToastEvenName is undefined 

```
/*
 * Copyright (c) 2018, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: MIT
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/MIT
 */
const ShowToastEventName = 'lightning__showtoast';

export class ShowToastEvent extends CustomEvent {
    constructor() {
        super(ShowToastEventName, {
            composed: true,
            cancelable: true,
            bubbles: true,
        });
    }
}
```

It would be good to have something like is in this repo:
https://github.com/trailheadapps/lwc-recipes/blob/master/force-app/test/jest-mocks/lightning/platformShowToastEvent.js

```
/**
 * For the original lightning/platformShowToastEvent mock that comes by default with
 * @salesforce/sfdx-lwc-jest, see:
 * https://github.com/salesforce/sfdx-lwc-jest/blob/master/src/lightning-stubs/platformShowToastEvent/platformShowToastEvent.js
 */

export const ShowToastEventName = 'lightning__showtoast';

export class ShowToastEvent extends CustomEvent {
    constructor(toast) {
        super(ShowToastEventName, {
            composed: true,
            cancelable: true,
            bubbles: true,
            detail: toast
        });
    }
}
```

Thanks for all your work, lwc is getting better every day!

**Comment by trevor-bliss** [comment]
I hear you about wanting the `ShowToastEventName` const exposed on the stub. Since it's not part of the public API of the `platformShowToastEvent` module, however, I don't think we should expose it as part of the default stub here.

I recommend using a custom stub like the lwc-recipes project does.
