### ISSUE TITLE
Feature Request: Need to test messageService

### ISSUE THREAD

**Issue by pchittum** [salesforce/sfdx-lwc-jest#144]
### Description
Lightning message service goes GA in Summer 20. To support `messageService` tests, create a stub for this here: 
https://github.com/salesforce/sfdx-lwc-jest/tree/master/src/lightning-stubs

**Comment by pozil** [comment]
Basic stub works. This issue can be closed.

**Comment by pmdartus** [comment]
Thanks for the follow-up @pozil
