### ISSUE TITLE
Wire function not called from test case

### ISSUE THREAD

**Issue by asennyey** [salesforce/sfdx-lwc-jest#146]
#### Steps to Reproduce

```js
// simplified test case
it("should display title", ()=>{
        // Create element
        const element = createElement('c-casedetails', {
            is: CaseDetails
        });

        document.body.appendChild(element);
        getRecordWireAdapter.emit(mockGetRecord);
        return Promise.resolve().then(()=>console.log("Wire console log should have triggered"))
    })
```

```html
<!-- HTML for component under test -->
<template>
<article if:true={contactData}
             class="slds-card slds-card_boundary">
</article>
</template>
```

```js
// JS for component under test
import { LightningElement } from 'lwc';

export default class Foo extends LightningElement {
    @wire(getRecord, {
        recordId: '$recordId',
        fields : ['Contact.Name']
    }) getContact(res){
        console.log(res)
    };

    get contactData(){return "test"}
}
```

```js
// Jest config overrides (if any)
No overrides
```

```bash
# Command to repro
lwc-jest
```

#### Expected Results

Wire adapter triggers  and console log called in component.

#### Actual Results

Console log never called.

### Version

-   @salesforce/sfdx-lwc-jest:  0.7.1
-   Node: 12.16.1

**Possible Solution**

**Additional context/Screenshots**

I have tried running the test files included in the lwc-recipe repo and those work, namely, 
WireGetRecordUser.

**Comment by trevor-bliss** [comment]
Hi @asennyey. I believe your component js code is missing some key lines for your example to work.  Namely, I don't see where `getRecord` or `recordId` are defined. 

The relevant lines from the `wireGetRecordUser` are 

```
import { getRecord, getFieldValue } from 'lightning/uiRecordApi';
import Id from '@salesforce/user/Id';
```

and

```
userId = Id;
```

You'll need something similar for the `recordId` you're trying to use.

I'm going to close this issue but feel free to re-open with an updated repro if you still experience issues.
