### ISSUE TITLE
Dependent install of Jest does not create node_modules/.bin/jest symlink

### ISSUE THREAD

**Issue by codefriar** [salesforce/sfdx-lwc-jest#155]
### Description

Greetings. Thank you for your work!
Yesterday I hit a weird issue and attempted to use the DebugTest runner in VSCode. I discovered that while I could run the Jest tests, I could not debug them. Investigating further led to the discovery of this issue. When Jest is included *only* as a dependency for sfdx-lwc-jest, no jest symlink is created in node_modules/.bin/jest. This causes the debugger to fail with a failure to find the jest binary.

So yeah. Running jest tests works, but debugging them doesn't, because no jest binary is found. 

Additionally, I tried altering a VSCode Launch.json file to point it at a -g installed version of jest in /usr/local/bin/jest but this change does not seem to be honored by sfdx-lwc-jest ?

#### Steps to Reproduce

These steps reference the specific sample app I was building tests for.

1. git clone git@github.com:trailheadapps/redwoods-insurance.git
2. cd redwoods-insurance/redwoods-insurance-salesforce/
3. git checkout prerelease/incidentMapTests
3. npm install
4. ls node_modules/.bin/

see the lack of jest symlink.

optionally use the debugger.

### Version

-   "@salesforce/sfdx-lwc-jest": "^0.9.1",
-   "node": ">= 10.13.0",

**Possible Solution**

manually include jest as a dev dependency - which can cause version issues

**Comment by pmdartus** [comment]
Jest is an internal dependency of `@salesforce/sfdx-lwc-jest`. Because of this, there is no guarantee that `node_modules/.bin/jest` to be present.

@codefriar I think that you are describing the symptom more than the issue itself. Could you confirm that you are running into this specific error when running `test:unit:debug` ?
