### ISSUE TITLE
Getting this error: Invalid LWC imported identifier "createElement" on a LWC test file when running force:deploy 

### ISSUE THREAD

**Issue by paintingemily** [salesforce/sfdx-lwc-jest#157]
### Description
We have added LWC Jest unit testing into our repo.  In the lwc component's test file we import "createElement", per the Salesforce Jest documentation. When we run our tests from the terminal, they pass. We have ```**/__tests__/**``` listed in our .forceignore file, so when I run "SFDX:Deploy Source to Org" from VS Code on my lwc folder to my personal sandbox, I receive no errors.
The problem occurs when we are using our CI/CD ADO pipeline to deploy our code to our dev sandbox (command force:deploy is run). It seems the test folder is not being ignored, and we receive this deploy error:
Invalid LWC imported identifier "createElement".

#### Steps to Reproduce

```js
import { createElement } from 'lwc';
import HelperTextList from 'c/helperTextList';
describe('c-helper-text-list', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });
    test('element has does not have comma when first item', () => {
        const element = createElement('c-helper-text-list', { is: HelperTextList });
        document.body.appendChild(element);
        // Property value is assigned after the component is inserted into the DOM
        element.index = 0;
        const span = element.shadowRoot.querySelector('span');
        
        // Use a promise to wait for asynchronous changes to the DOM
        return Promise.resolve().then(() => {
            expect(span.textContent).not.toBe(', ');
        });
    });
    test('element has does have comma when second item', () => {
        const element = createElement('c-helper-text-list', { is: HelperTextList });
        element.index = 1;
        document.body.appendChild(element);
        
        // Use a promise to wait for asynchronous changes to the DOM
        return Promise.resolve().then(() => {
            const span = element.shadowRoot.querySelector('.comma');
            expect(span.textContent).toBe(', ');
        });
    });
});
```

```html
<!-- HTML for component under test -->
<template>
    <span class="comma" if:true={hasMultiple}>, </span>
    <span><slot></slot></span>
</template>
```

```js
import { LightningElement, api } from 'lwc';

export default class HelperTextList extends LightningElement {
    @api index;
    hasMultiple = false;
    renderedCallback() {
        if (this.index >= 1) {
            this.hasMultiple = true;
        }
    }
}    
```

```.forceignore
# List files or directories below to ignore them when running force:source:push, force:source:pull, and force:source:status
# More information: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_exclude_source.htm
#

package.xml

# LWC configuration files
**/jsconfig.json
**/.eslintrc.json


# LWC Jest
**/__tests__/**
```

```bash
sfdx force:deploy
```

#### Expected Results

Files are deployed to the sandbox and the __test__ files are ignored.

#### Actual Results

Deployment fails, error: 
2020-07-16T19:28:13.5612990Z Error  force-app\main\default\lwc\helperTextList\__tests__\helperTextList.test.js  [Line: 1, Col: 9] LWC1518: Invalid LWC imported identifier "createElement"
2020-07-16T19:28:13.6151707Z ERROR running force:source:deploy:  Deploy failed.

### Version

-   @salesforce/sfdx-lwc-jest: ^0.7.1
-   Node: ^6.9.0

**Possible Solution**

**Additional context/Screenshots**

<img width="580" alt="Screen Shot 2020-07-17 at 11 50 36 AM" src="https://user-images.githubusercontent.com/8031167/87820908-c6075000-c823-11ea-9af7-5aaa87f630c5.png">

**Comment by pmdartus** [comment]
The deployment fails because importing `createElement` from `lwc` on the platform is not allowed. 
Based on the error message, the following LWC module is published on the platform `force-app\main\default\lwc\helperTextList_tests_\helperTextList.test.js`. This module doesn't match the `**/__tests__/**` pattern in your `.forceignore` and this is why SFDX pushes it.

It is hard to tell from your issue how your repository is structured. That being said, we recommend collocating your LWC module code with the associated. The tests should be under the `__tests__` directory in the LWC module folder. I would expect the test file path to be: `force-app\main\default\lwc\helperTextList\_tests_\helperTextList.test.js` (note the extra backslash in the file path). This way it will be properly ignored by SFDX.

**Comment by paintingemily** [comment]
@pmdartus I think that's a styling issue with how git is showing the code, this is the error path:
```force-app\main\default\lwc\helperTextList\__tests__\helperTextList.test.js```
The test is located in a folder called ```__tests__``` inside of the component's folder, as recommended. We have also tried explicitly linking to it in our forceignore file (trying both forward slashes and backslashes for the directory)

**Comment by paintingemily** [comment]
Can this plugin be configured so the test files can be placed outside of the "lwc" folder?

**Comment by pmdartus** [comment]
> Can this plugin be configured so the test files can be placed outside of the "lwc" folder?

I don't think it is possible. Otherwise, you will run into resolution issues when jest will attempt to resolve your LWC modules. 

Based on the information you shared, I still think it's either a configuration issue or a file naming issue. Could you share minimal SFDX project exhibiting this issue so we can attempt to reproduce it?

**Comment by trevor-bliss** [comment]
@paintingemily Could you also please clarify what SFDX command the CI is running? The original post says `sfdx force:deploy` but that's not a valid command.

**Comment by muenzpraeger** [comment]
Did you try it with a regular `\` instead of a forward slash in the ignore pattern?

**Comment by paintingemily** [comment]
@trevor-bliss this is the specific command the CI is running: 
```sfdx force:source:deploy --targetusername Dev --manifest ./manifest/package.xml --loglevel info --wait 60```

@muenzpraeger Yes. We tried specifically listing out the file in the forceignore with:
```force-app\main\default\lwc\helperTextList\__tests__\helperTextList.test.js```
Same error.

@pmdartus -- Are you asking for a simplified zip of our project? I might be able to work on that in a bit.  We also have a meeting with Salesforce support this afternoon to try to debug the issue, I'll update here if we find a resolution.

**Comment by muenzpraeger** [comment]
@clairebianchi

**Comment by paintingemily** [comment]
Just finished call with Salesforce support, no resolution either.  She will be checking with her team and getting back to us.

Our current theory is it might be an issue with Azure DevOps (what we use for our pipeline).

**Comment by pmdartus** [comment]
> Are you asking for a simplified zip of our project?

Yes, that would help. Did you try running the deployment on another CI (Jenkins, Travis, CircleCI, ...) to see if the same issue is reproducible?

**Comment by paintingemily** [comment]
Unfortunately, I'm not able to try deployment on another CI.  
Here is a _super_ simplified version of our repo, I removed all aura/apex/other lwc components as they shouldn't be part of the issue here. https://github.com/paintingemily/lwc-jest-test

**Comment by aheber** [comment]
@paintingemily, I've opened a PR against your report with what should be the fix (worked on my machine...)
https://github.com/paintingemily/lwc-jest-test/pull/1

Please try it out and let us know.

**Comment by paintingemily** [comment]
@aheber Hmm, I'm not sure why my .forceignore was blank like that -- the file we use has more lines, I've pushed up what we have tried to Master branch.  Although, we have not tried specifically leading with ```force-app/```

**Comment by paintingemily** [comment]
@aheber -- we just tried using your forceignore addition, but we get the same error:
<img width="1253" alt="Screen Shot 2020-07-27 at 2 44 05 PM" src="https://user-images.githubusercontent.com/8031167/88595407-ba800a00-d017-11ea-8227-938cead107f1.png">

**Comment by paintingemily** [comment]
If it helps, these are all the variations we have tried now in our ```.forceignore``` file:

> ```**/__tests__/**```
> ```**\__tests__\**```
> ```force-app/**/__tests__/**```
> ```force-app\main\default\lwc\helperTextList\__tests__\helperTextList.test.js```
> ```force-app\main\default\lwc\helperTextList\__tests__\```
> ```force-app/main/default/lwc/helperTextList/__tests__/helperTextList.test.js```

**Comment by aheber** [comment]
@paintingemily, are you able to retrieve the DX version number running in your CI environment? `sfdx plugins --core` would be helpful just for review and sanity check.

Do these problems manifest on your computer at all or only in the CI environment?

For what it is worth, I think you'll want to make sure you're sticking with the `/` which I do see in some of your examples. That is compatible with Windows, MacOS, & Linux where the `\` is typically Windows only and I've had problems with it before.

**Comment by paintingemily** [comment]
@aheber this is what is returned for dx version:
@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.0.1 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.7.10 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.0.7 (core)
analytics 1.12.0 (core)
generator 1.1.3 (core)
salesforcedx 48.22.11 (core)
├─ salesforce-alm 48.24.3 (core)
├─ custom-metadata 1.0.4 (core)
├─ salesforcedx-templates 48.18.0 (core)
└─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
sfdx-cli 7.65.6 (core)

This problem does not manifest on my computer locally when deploying via VS Code.  I only see the issue in CI process in ADO.

Yeah the forward slash is what I thought also (and was the first thing we tried, following docs for this plugin), but we tried the other way just to try since the CI process is on Linux I think.

**Comment by aheber** [comment]
That is the version from the CI system?
It isn't too old but isn't the most recent by a few weeks if memory serves. Any ability to update it just to make sure?

I'm just reaching for anything that causes it to behave differently on your machine vs. the CI system. Sorry if I'm taking you through activities you've already dug into.

**Comment by paintingemily** [comment]
@aheber -- Apparently that version is from my local/VS Code, I assumed it was the same as CI.  In our pipeline, we do a fresh install every time of sfdx -- so the last release shows version: sfdx-cli@7.66.2

**Comment by paintingemily** [comment]
After we started having this issue our DevOps engineer also added installing this package to our pipeline (after the sfdx install) in case it would help, but it hasn't made a difference. (I'm also not sure why it would need it when really we just need the test files to be ignored)

**Comment by aheber** [comment]
@paintingemily, if it would help I'd be happy to get on a screen share today and take a look. I think we're still missing some key replication step to be able to resolve this and I don't know what it is.

Unless you can get your sample project to a place where it is throwing the error, after I added that line to the `.forceignore` I wasn't able to replicate the problem anymore so I ran out of stuff to chase on it.

If you push your sample project through the same pipeline do you get the same problems?

**Comment by paintingemily** [comment]
@aheber Sorry for the delay.  Thanks for the offer of screen share, I think that could definitely be helpful. We have other priorities/releases this week -- would we be able to set up a time to screen share next week? (You can email me at e.painter@f5.com)

**Comment by brianesel** [comment]
@paintingemily  So I have been try this : `force-app/**/__test__/**` into forceignore and its working just fine. I don't know why `force-app/**/__test__/**`

**Comment by pmdartus** [comment]
Thanks for sharing the repo @paintingemily.
Could you also set up an Azure pipeline similar that yours to have a full end-to-end reproduction environment? This would greatly help the investigation.

**Comment by aheber** [comment]
@paintingemily and I worked and found that their deployment pipeline was configured to drop the `.forceignore` file along the way. Ensuring the file progressed through the phases appears to have resolved the issue.

Waiting on @paintingemily to confirm and close.

**Comment by paintingemily** [comment]
Confirmed.  Thanks for your help @aheber !

**Comment by MrAnonymous29** [comment]
@paintingemily I'm also getting the same error as you...
Can you/anyone
![Error](https://github.com/salesforce/sfdx-lwc-jest/assets/154501868/ad4822ff-34f1-40bd-adb0-3b8a24d59195)
 help me with this issue?
