### ISSUE TITLE
npm ERR! Failed at the salesforce-app@1.0.0 test:unit script

### ISSUE THREAD

**Issue by jeremyesjohnson** [salesforce/sfdx-lwc-jest#160]
### Description
I'm trying to complete the Lightning Web Components Tests  > [Set Up Jest Testing Framework](https://trailhead.salesforce.com/en/content/learn/modules/test-lightning-web-components/set-up-jest-testing-framework) trailhead unit. When I run the command

`npm run test:unit`

I get an error:

```
C:\Users\~\LWC Testing\test-lwc>npm run test:unit

> salesforce-app@1.0.0 test:unit C:\Users\~\LWC Testing\test-lwc
> sfdx-lwc-jest

No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In C:\Users\~\LWC Testing\test-lwc
  1 file checked.
  testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x) - 0 matches
  testPathIgnorePatterns: C:\\Users\\~\\LWC Testing\\test-lwc\\node_modules\\, C:\\Users\\~\\LWC Testing\\test-lwc\\test\\specs\\ - 1 match
  testRegex:  - 0 matches
Pattern:  - 0 matches
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! salesforce-app@1.0.0 test:unit: `sfdx-lwc-jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the salesforce-app@1.0.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\~\AppData\Roaming\npm-cache\_logs\2020-07-23T21_38_10_726Z-debug.log
```

#### Steps to Reproduce
Create a Salesforce DX Project
`SFDX: Create Project > test-lwc`

Install Node.js and npm
```
node --version: v12.18.3
npm --version: 6.14.6
```

Install sfdx-lwc-jest Node Module
`sfdx force:lightning:lwc:test:setup
Queueing addition of test scripts to package.json...
Jest configuration found in jest.config.js. Skipping creation of new config file.
Updating files...
logFileUpdatesEnd
Installing @salesforce/sfdx-lwc-jest node package...
npm WARN deprecated rollup-plugin-replace@2.2.0: This module has moved and is now available at @rollup/plugin-replace. Please update your dependencies. This version is no longer maintained.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\jest-haste-map\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @salesforce/eslint-config-lwc@0.7.0 requires a peer of eslint@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-compat@3.3.0 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-import@2.20.2 requires a peer of eslint@2.x - 6.x but none is installed. You must install peer dependencies yourself.

+ @salesforce/sfdx-lwc-jest@0.7.1
updated 1 package and audited 1033 packages in 21.877s

28 packages are looking for funding
  run `npm fund` for details

found 2 vulnerabilities (1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Test setup complete.
`

Add scripts to package.json
```
  "scripts": {
    "lint": "npm run lint:lwc && npm run lint:aura",
    "lint:aura": "eslint **/aura/**",
    "lint:lwc": "eslint **/lwc/**",
    "test": "npm run test:unit",
    "test:unit": "sfdx-lwc-jest",
    "test:unit:watch": "sfdx-lwc-jest --watch",
    "test:unit:debug": "sfdx-lwc-jest --debug",
    "test:unit:coverage": "sfdx-lwc-jest --coverage",
    "prettier": "prettier --write \"**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}\"",
    "prettier:verify": "prettier --list-different \"**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}\""
  },
```

Run the script (this works fine; note, there are no tests yet)
`>node node_modules/@salesforce/sfdx-lwc-jest/bin/sfdx-lwc-jest`

Run all tests (this produces the error)
`npm run test:unit`

#### Expected Results

No tests found, exiting with code 1

#### Actual Results

```
> salesforce-app@1.0.0 test:unit C:\Users\~\LWC Testing\test-lwc
> sfdx-lwc-jest

No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In C:\Users\~\LWC Testing\test-lwc
  1 file checked.
  testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x) - 0 matches
  testPathIgnorePatterns: C:\\Users\\~\\LWC Testing\\test-lwc\\node_modules\\, C:\\Users\\~\\LWC Testing\\test-lwc\\test\\specs\\ - 1 match
  testRegex:  - 0 matches
Pattern:  - 0 matches
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! salesforce-app@1.0.0 test:unit: `sfdx-lwc-jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the salesforce-app@1.0.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\~\AppData\Roaming\npm-cache\_logs\2020-07-23T21_38_10_726Z-debug.log
```

The log file:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'test:unit'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'pretest:unit', 'test:unit', 'posttest:unit' ]
5 info lifecycle salesforce-app@1.0.0~pretest:unit: salesforce-app@1.0.0
6 info lifecycle salesforce-app@1.0.0~test:unit: salesforce-app@1.0.0
7 verbose lifecycle salesforce-app@1.0.0~test:unit: unsafe-perm in lifecycle true
8 verbose lifecycle salesforce-app@1.0.0~test:unit: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\~\LWC Testing\test-lwc\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Git\cmd;C:\Program Files\NVIDIA Corporation\NVIDIA NGX;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\WorldPainter;C:\Program Files\RedHat\java-1.8.0-openjdk-1.8.0.252-2\bin;C:\Program Files\RedHat\java-1.8.0-openjdk-1.8.0.252-2\jre\bin;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\nodejs\;C:\dev\tools\Ruby25-x64\bin;C:\Users\jerem\AppData\Local\Microsoft\WindowsApps;C:\Users\jerem\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Salesforce CLI\bin;C:\Program Files\Java\jdk-12.0.1\bin;C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.1\bin;C:\Users\jerem\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\DataGrip 2019.3.4\bin;C:\Users\jerem\AppData\Local\GitHubDesktop\bin;C:\Users\jerem\AppData\Roaming\npm
9 verbose lifecycle salesforce-app@1.0.0~test:unit: CWD: C:\Users\~\LWC Testing\test-lwc
10 silly lifecycle salesforce-app@1.0.0~test:unit: Args: [ '/d /s /c', 'sfdx-lwc-jest' ]
11 silly lifecycle salesforce-app@1.0.0~test:unit: Returned: code: 1  signal: null
12 info lifecycle salesforce-app@1.0.0~test:unit: Failed to exec test:unit script
13 verbose stack Error: salesforce-app@1.0.0 test:unit: `sfdx-lwc-jest`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid salesforce-app@1.0.0
15 verbose cwd C:\Users\~\LWC Testing\test-lwc
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:unit"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error salesforce-app@1.0.0 test:unit: `sfdx-lwc-jest`
22 error Exit status 1
23 error Failed at the salesforce-app@1.0.0 test:unit script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

### Version

- node --version: v12.18.3
- npm --version: 6.14.6
- @salesforce/sfdx-lwc-jest@0.7.1

**Comment by trevor-bliss** [comment]
Based on the log `No tests found, exiting with code 1`, it sounds like you do not have a test case to run or it's not named properly. 

In your project if you have an LWC component named `hello` at
```
force-app/main/default/lwc/hello
```

your test file should be at
```
force-app/main/default/lwc/hello/__tests__/hello.test.js
```

You can see an example in lwc-recipes here: https://github.com/trailheadapps/lwc-recipes/blob/master/force-app/main/default/lwc/hello/__tests__/hello.test.js

**Comment by jeremyesjohnson** [comment]
Thanks, Trevor. Can confirm. In the next trailhead unit, we add unit tests. Interestingly, the npm error message is displayed if any of the tests fail, but doesn't display if they all pass. sfdx-lwc-jest seems to run properly regardless. It's just confusing to a newcomer.
