### ISSUE TITLE
Slow test execution on large projects due to getModulePaths glob pattern

### ISSUE THREAD

**Issue by NTaylor1993** [salesforce/sfdx-lwc-jest#161]
### Description
In a large project (>15,000 files under force-app) test execution is becoming increasingly slow. After some investigation I have seemingly tracked the root cause to the Glob pattern in the `getModulePaths()`  function of `project.js` this seems to scan every file that is under a project root folder for each module that imported into a test to build the list of relative paths to every LWC folder within those roots.

This causes incredibly slow runs whether running single tests or the entire suite. During my investigation into why I was seeing such slow tests I changed this method to just return a predetermined list of the paths and this resulted in a reduction in the runtime of the entire test suite from ~450-500s to ~40-50s approximately a 10 times reduction in execution time.

Upon further investigation I have found the biggest slowdown comes from the resolver that is being used, as this is where the `getModulePaths` method is being called from each time a new module is being imported. I have had some luck mitigating the impact of this by creating a custom resolver based off of the one from this project that uses a predefined list of paths, it would be good however not to have to use a custom resolver as this could get out of sync with future updates requiring further maintenance.
### Version

-   @salesforce/sfdx-lwc-jest: 0.9.2
-   Node: v12.16.3

**Possible Solution**

One possible solution would be caching the result of the initial run of `getModulePaths()` and saving this for the lifecycle of the test run, this would cause a slow start as this list was build once (possibly once per worker) followed by much faster tests subsequently as the cached version is uses.

Alternatively a config file could be introduced that allows the developer to specify the LWC files to scan, favouring that list of files if the config exists and specifies the list and only building the list if that is missing. Something along the lines of

````
// get relative path to 'lwc' directory from project root
function getModulePaths() {
	const lwcJestConfig = path.join(PROJECT_ROOT,'sfdx-lwc-jest.config.js')

	let paths = [];

	if (fs.existsSync(lwcJestConfig)) {
		const { lwcPaths } = require(lwcJestConfig)

		if (lwcPaths) {
			return lwcPaths;
		}
	}
	const projectPaths = [];
	const packageDirectories = getSfdxProjectJson().packageDirectories;

	packageDirectories.forEach(entry => {
		projectPaths.push(entry.path);
	});

	for (let i = 0; i < projectPaths.length; i++) {
		const found = new GlobSync('**/lwc/', { cwd: projectPaths[i] }).found;
		for (let j = 0; j < found.length; j++) {
			paths.push(path.join(projectPaths[i], found[j]));
		}
	}

	return paths;
}
````

Would either of these solutions be possible to implement as the gains in test exception time, especially for CI builds can be monumental here. 

Edit: Updated cause of problem upon further investigation.

**Comment by lukecotter** [comment]
I have made a change with your suggested caching approach #164
I saw times for a suite to run go from 5.5 minutes to 20 seconds.
Really nice catch @NTaylor1993

**Comment by NTaylor1993** [comment]
@lukecotter thanks for that, really does make a massive difference to the runtime.
