### ISSUE TITLE
Failed to install sfdx-lwc-jest

### ISSUE THREAD

**Issue by techopse2e** [salesforce/sfdx-lwc-jest#162]
### Description
When i start to install sfdx-lwc-jest in Node(10.15.3), it failed with error message "404 Not Found: @salesforce/sfdx-lwc-jest@latest"

#### Steps to Reproduce

```bash
npm i @salesforce/sfdx-lwc-jest
```

#### Expected Results

success

#### Actual Results

npm ERR! code E404
npm ERR! 404 Not Found: @salesforce/sfdx-lwc-jest@latest

### Version

-   @salesforce/sfdx-lwc-jest: latest
-   Node: 10.15.3

**Comment by muenzpraeger** [comment]
It is an npmjs issue and should be fixed soon. => https://status.npmjs.org/

**Comment by techopse2e** [comment]
Thanks @muenzpraeger
