### ISSUE TITLE
Feat: add support for API v50.0

### ISSUE THREAD

**Issue by pozil** [salesforce/sfdx-lwc-jest#170]
With 228 approaching, the Dev EV team is working on upgrading all sample apps.
Could you make sure that we have access to a sfdx-lwc-jest NPM prelease that supports API v50.0?

**Comment by ravijayaramappa** [comment]
@pozil winter21 version can be fetch here https://www.npmjs.com/package/@salesforce/sfdx-lwc-jest/v/0.10.0

**Comment by pozil** [comment]
Awesome, thanks @ravijayaramappa
