### ISSUE TITLE
[BUG] LWC Jest 

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/sfdx-lwc-jest#182]
### Description
When I run `npm run test:unit` Jest is executing "Magical" test suites I don't even have on my project. This issue is only happening on my computer. When I do a new checkout on a container and run the tests inside it, all the tests pass without a problem and Jest does not create all those weird magical test suits called "test.js". On the image below you can see jest ran 54 test suites while we only created 6! And all these 6 executed with success.

![image](https://user-images.githubusercontent.com/55927613/99511164-d1a88600-297f-11eb-96db-9ef65d4bf29a.png)

I could not find a `lwc-jest` repository, so Im opening the issue here.

#### Steps to Reproduce
It only happens on my computer. I don't know how to reproduce it.

#### Expected Results
Jest tests suites should execute without a problem anywhere.

#### Actual Results
Jest is creating magical test suites I did not create when I execute ``npm run test:unit` called "test.js" and all of them are failing. My test suites pass with success.

### Browsers Affected
not applicable

**Comment by pmdartus** [comment]
Thanks for reporting this issue @AllanOricil. I transferred it to the appropriate repository.
It's the first time I hear about this issue. It will be impossible for us to investigate it without any concrete repro steps.

Please update the issue description with some minimal reproduction steps (a simple SFDX project). Until then I close this issue.

**Comment by AllanOricil** [comment]
> Thanks for reporting this issue @AllanOricil. I transferred it to the appropriate repository.
> It's the first time I hear about this issue. It will be impossible for us to investigate it without any concrete repro steps.
> 
> Please update the issue description with some minimal reproduction steps (a simple SFDX project). Until then I close this issue.

@pmdartus 
This is the problem haha
It only happens on my computer.  A colleague checked out the repo and everything is running ok to them. 
I can copy the folder and share with you. Maybe this will work. Where can I send you a google drive link privately?

**Comment by pmdartus** [comment]
I would prefer to keep the discussion on Github for tracking purposes.
Is it something that you can reproduce on a new SFDX repository?

**Comment by AllanOricil** [comment]
@pmdartus 
I cloned the repo again on a separate folder and then the error was gone. But clearly something is happening only on the other folder. If I can't share the folder privately for your team to investigate, then the bug will remain and will impact somebody else in the future, since I can't reproduce it. I really don't have any ideas on how that bug is possible, or if it is or not a sfdx bug or vscode extension bug, or even a Jest bug. Really weird :/

![image](https://user-images.githubusercontent.com/55927613/99551906-50b7b180-29b4-11eb-98c4-dd2b6caf87a6.png)

**Comment by trevor-bliss** [comment]
@AllanOricil I'm not sure what's going on with the rogue tests being run, but if it keeps giving you trouble you can consider [overriding the Jest config](https://github.com/salesforce/sfdx-lwc-jest#overriding-jest-config) to have a more specific test file matcher. 

There's a couple different ways to accomplish this via config. One example would be to use the [`testMatch`](https://jestjs.io/docs/en/configuration#testmatch-arraystring) option to **only** look for tests inside your `__tests__` directories.

**Comment by AllanOricil** [comment]
@pmdartus FInally understood how to reproduce it. It is related to the dev server. The magical tests are comming from the Local Dev Server. Because Im the only one using it and I only ran the dev server in that folder that had the error, this happened.
How can I tell JEST to exclude the Tests from the bundled Dev Server source code?

![image](https://user-images.githubusercontent.com/55927613/99659072-3df6b880-2a58-11eb-925c-720ab7d6c8fd.png)

**Comment by AllanOricil** [comment]
@pmdartus I included the .localdevserver to testPathIgnorePatterns prop on jest.config.js and it worked.  I think you guys can include it on the default `sfdx-lwc-jest/config` so people don't face the same problem like I did.

````js
const { jestConfig } = require('@salesforce/sfdx-lwc-jest/config');
module.exports = {
  ...jestConfig,
  displayName: 'DCE-DESIGN_COMPONENTS',
  setupFiles: ['<rootDir>/jest-mocks/jestSetup.js'],
  testPathIgnorePatterns: ['/node_modules/', '/include/', '/.localdevserver/'],
  moduleNameMapper: {}
};

````
