### ISSUE TITLE
Add the ability to resolve paths not from the sfdx-project file

### ISSUE THREAD

**Issue by BenBozou** [salesforce/sfdx-lwc-jest#185]
### Description

I would like to be able to resolve modules that are not in my sfdx-project.json directories.
Use-case:
We are building multiple 2GP that are all in the same namespace. One of them is a common base for others. In this common package, we have a lot of components that are reused by our dependent packages.
We are not willing to mock all of them and would like a way to add an external folder to the resolver.js paths.
(this external folder would be part of the project root and imported as a git submodule)

Could this make sense as an enhancement (or maybe it is already possible and I'm completely missing something?)

### Version

-   @salesforce/sfdx-lwc-jest: x.x.x
-   Node: x.x.x

**Possible Solution**

In poject.js

```
function getModulePaths() {
    const paths = [];
    const projectPaths = [];
    const packageDirectories = getSfdxProjectJson().packageDirectories;

    packageDirectories.forEach((entry) => {
        projectPaths.push(entry.path);
    });

    projectPaths.push('other/folder/path'); // Could be a list of folders

    for (let i = 0; i < projectPaths.length; i++) {
        const found = new GlobSync('**/lwc/', { cwd: projectPaths[i] }).found;
        for (let j = 0; j < found.length; j++) {
            paths.push(path.join(projectPaths[i], found[j]));
        }
    }

    return paths;
}
```

**Comment by pmdartus** [comment]
I am not familiar with 2GP file structure. Could you share an example?

This project really aims to simplify test setup and configuration for the standard SFDX setup. This project is nothing more than a thin wrapper on top of [lwc-test](https://github.com/salesforce/lwc-test). For more complex folder structures I would recommend setting up jest and [@lwc/jest-preset](https://lwc.dev/guide/test#unit-tests) manually.

Thoughts @trevor-bliss ?

**Comment by muenzpraeger** [comment]
IMHO the way that you built your custom resolve mechanism for the module paths is the way to go. Personally I don't see a standard behavior that would make sense to be implemented.

What an option could be [although not verified] is to add your "common" package as package dependency in your `sfdx-project.json`, and point from there to your additional local folder.

**Comment by BenBozou** [comment]
Thanks @pmdartus @muenzpraeger 

Our common package is already a dependency in our project file, but the dependency is to a built package, not to the source folder. Thus, the standard resolver is not considering it.

If you think about customer building multiple unlocked packages, the requirement could be the same. Not limited to ISVs and Salesforce building managed packages

**Comment by muenzpraeger** [comment]
The controlling mechanism for tooling is the `sfdx-project.json` configuration. That configuration is what the tooling builds upon. The dependency configuration is primarily for defining the dependency graph for your individual packages, and building packages. But it is not the sole purpose.

My recommendation was to define the `path` key in the dependency - relative to the current project, so in your example `../other/folder/path`. As all `path` values are evaluated by the default resolver this should add your folder to the resolver.

Another option, and eventually more elegant, is to map the components that you want to mock via your `jest.config.js`. Similar to what we did [here](https://github.com/trailheadapps/easy-spaces-lwc/blob/develop/jest.config.js#L7).

**Comment by pmdartus** [comment]
After discussion with @trevor-bliss and based on the previous comments, I think that we align on the fact that we want to keep this project tailored toward standard/simple SFDX project structure.
