### ISSUE TITLE
GitHub dependabot creating alerts due to dependency on node-notifier versions < 8.0.1

### ISSUE THREAD

**Issue by seanpat09** [salesforce/sfdx-lwc-jest#186]
### Description
Projects that include sfdx-lwc-jest are getting tagged by dependabot as having an vulnerability due to a dependency on node-notifier versions < 8.0.1

#### Steps to Reproduce
The yarn.lock file includes `node-notifier@^6.0.0` - https://github.com/salesforce/sfdx-lwc-jest/blob/master/yarn.lock#L4594

Running `yarn why node-notifier` returns the following:
```
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "node-notifier"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "node-notifier@6.0.0"
info Reasons this module exists
   - "jest#@jest#core#@jest#reporters" depends on it
   - Hoisted from "jest#@jest#core#@jest#reporters#node-notifier"
info Disk size without dependencies: "5.63MB"
info Disk size with unique dependencies: "5.86MB"
info Disk size with transitive dependencies: "5.92MB"
info Number of shared dependencies: 6
✨  Done in 0.58s.
```

Tracing these dependencies and you eventually get to salesforce/sfdx-lwc-jest depending on `jest@25.5.4`

#### Expected Results

No dependabot alerts

#### Actual Results

Dependabot alerts project as having an vulnerability due to a dependency on node-notifier versions < 8.0.1

### Version

-   @salesforce/sfdx-lwc-jest: v0.10.2
-   Node: v15.4.0

**Possible Solution**

Is it possible to upgrade the Jest dependency version in this project? Alternatively, would there be an issue including a `resolutions` block to force the version upgrade in our projects?

```
"resolutions": {
    "node-notifier": "^8.0.1",
}
```

**Comment by davidmreed** [comment]
If I may tag on to @seanpat09's summary: 

This is one manifestation of a larger challenge with lwc-jest that Salesforce.org has encountered on several occasions: the combination of 

- a 1:1 relationship between lwc-jest versions and Salesforce API versions, and
- out-of-date dependencies on older lwc-jest versions 

causes significant maintenance impact to our suite of 39+ managed packages.

I have a lengthier writeup that I'd love to discuss with Sean and y'all if you're open to reviewing with us. Thank you!
