### ISSUE TITLE
--skipApiVersionCheck  flag is not available anymore

### ISSUE THREAD

**Issue by burakqa** [salesforce/sfdx-lwc-jest#194]
#### Steps to Reproduce

When I ran the following command on my VS Code LWC project's top folder

> node_modules/@salesforce/sfdx-lwc-jest/bin/sfdx-lwc-jest

I got this error

             error Invalid sourceApiVersion found in sfdx-project.json. Expected 49.0, found 50.0

In your documentation, you suggested using skipApiVersionCheck flag to avoid the sourceApiVersion  cheeck,  but that flag is not available.

Please advise.

**Comment by pmdartus** [comment]
This flag is not yet exposed. We recently merged the addition of this flag and updated the `README.md` but we haven't cut a new release yet ([commit history](https://github.com/salesforce/sfdx-lwc-jest/commits/master)). This flag will be available with the next release of `@salesforce/sfdx-lwc-jest`.
