### ISSUE TITLE
Remove the header from the sfdx-lwc-jest -- --json output

### ISSUE THREAD

**Issue by AllanOricil** [salesforce/sfdx-lwc-jest#203]
### Description

I think sfdx-lwc-jest is outputing a header when running `sfdx-lwc-jest -- --json`

#### Steps to Reproduce

1 - run `sfdx-lwc-jest -- --json > results.json`
2 - check that the output contains this header that seems to be added by sfdx-lwc-jest 

![image](https://user-images.githubusercontent.com/55927613/110940654-26a54900-832f-11eb-93fa-4e2e678e0fa9.png)

### Version

-   @salesforce/sfdx-lwc-jest: 0.7.1
-   Node: 12.13.1

**Possible Solution**

Remove that header

**Comment by AllanOricil** [comment]
When I run the problem is solved

`sfdx-lwc-jest -- --json --outputFile=jest.json`

**Comment by muenzpraeger** [comment]
That is the default Jest output, and not specific to `sfdx-lwc-jest`.

See the documentation [here](https://jestjs.io/docs/cli#--json).
