### ISSUE TITLE
Add support to pass in custom config file 

### ISSUE THREAD

**Issue by mattgoldspink** [salesforce/sfdx-lwc-jest#26]
Unfortunately a lot of our code base is pre-sfdx so it doesn't conform to the sfdx project structure. We have a well established build process that generates a lot of the config files we need and I'm adding support for lwc-jest. It looks like lwc-jest only accepts a custom `jest.config.js` in the root of the project. It would be great if we could pass in a different path to it. For example:

`lwc-jest --config=./tmpdir/jest.config.js`

At the moment this doesn't get passed through. Similarly I tried:

`lwc-jest -- --config=./tmpdir/jest.config.js`

But looking at the code it looks like you will only pass through a config that's in the root directory of the project.

Ideally if someone overrides it on the CLI you'd pass that through to jest. I'm happy to create a PR for this since we need it and I can test. Which of the above 2 options would be best?

**Comment by wilsonmar** [comment]
I just installed this on my Mac Yosemite running Node v9.11.1. Below is the message returned when I run on a blank folder:

```
npm install @salesforce/lwc-jest --save-dev 
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
```

**Comment by pmdartus** [comment]
I like better the approach with the extra double dashes `lwc-jest -- --config=./tmpdir/jest.config.js`. It makes clear the intent to pass the configuration to the underlying jest CLI and not to the lwc-jest CLI.

I would defer the decision to @trevor-bliss.

**Comment by trevor-bliss** [comment]
Yes I agree, I like the double dash as a passthrough directly to Jest. Then we can update our logic in [test-runner.js](https://github.com/salesforce/lwc-jest/blob/master/src/utils/test-runner.js#L52) to check if the user passed in the config option or not when we decide to use our default config or not.

**Comment by trevor-bliss** [comment]
Hi @mattgoldspink. Is this still something you plan on creating a PR for? No worries if not, just trying to prevent duplicated work if you are.

**Comment by trevor-bliss** [comment]
Please comment or reopen if this is still an issue.
