### ISSUE TITLE
Versions are out of sync between GitHub and npm

### ISSUE THREAD

**Issue by pozil** [salesforce/sfdx-lwc-jest#264]
Latest version on [GitHub](https://github.com/salesforce/sfdx-lwc-jest/releases) is `1.0.1`
Latest version on [npm](https://www.npmjs.com/package/@salesforce/sfdx-lwc-jest) is `1.1.0` with `latest` tag

Also, the readme refers to a `prerelease` tag that does not exist in npm. The closest to this is a `next` tag but it's outdated.

**Comment by nolanlawson** [comment]
1.1.0 is now in GitHub: https://github.com/salesforce/sfdx-lwc-jest/releases/tag/v1.1.0
