### ISSUE TITLE
Create element throws error when lwc has light DOM enabled

### ISSUE THREAD

**Issue by terry-lewis-sf** [salesforce/sfdx-lwc-jest#273]
#### Steps to Reproduce

```html
<template  lwc:render-mode='light'>
    <div class="hello">
    </div>
</template>
```

```js
// JS for component under test
import { LightningElement } from 'lwc';

export default class Foo extends LightningElement {
    static renderMode = 'light';
    ...
}
```

```js
// Jest test for component under test
 import { createElement } from 'lwc';
 import TestLwc from 'c/testLwc';

describe('c-test-lwc', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
         const element = createElement('c-test-lwc', {
             is: TestLwc
        });
    });
});
};
```

#### Expected Results

element is created

#### Actual Results

Error: Assert Violation: TestLwc is an invalid LWC component. Light DOM  components are not available in this environment.

### Version

-   @salesforce/sfdx-lwc-jest:0.13.0
-   Node: 16.14.2

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/102820139/165844182-014a1771-6a06-4013-a2fd-cf156166d6a6.png)

**Comment by pmdartus** [comment]
The version of LWC included in `@salesforce/sfdx-lwc-jest` v0.13.0 doesn't have light DOM enabled. Updating to the latest version of `@salesforce/sfdx-lwc-jest` will fix this issue.

**Comment by alvin-tayag** [comment]
@pmdartus graceful-fs is throwing "global is not defined"

**Comment by pmdartus** [comment]
@alvin-tayag Thanks for opening this issue. Could you please open a separate issue with detailed repro steps for us to investigate?
