### ISSUE TITLE
Latest npm version re-introduces wrong API version check

### ISSUE THREAD

**Issue by lchnnl** [salesforce/sfdx-lwc-jest#276]
Description
The latest version from npm (1.1.0 as of writing this) still uses API version 53.0 as baseline.

Invalid sourceApiVersion found in sfdx-project.json. Expected 53.0, found 54.0

Steps to Reproduce
Change a SFDX projects API version to 54.0 (Spring '22)
Install @salesforce/sfdx-lwc-jest@latest from npm.
Run Jest tests
Expected Results
Tests run successful.

Actual Results
The Jest invocation exists with Invalid sourceApiVersion found in sfdx-project.json. Expected 53.0, found 54.0.

Version
@salesforce/sfdx-lwc-jest: 1.1.0

**Comment by yippie** [comment]
And now API version 55 is out. If they aren't going to make a new sfdx-lwc-jest every new salesforce release, then the version check needs to go away as it is clear sfdx-lwc-jest is not actually intended or maintained in anything resembling a version locked state.

**Comment by ravijayaramappa** [comment]
Should be fixed by updating to `@salesforce/sfdx-lwc-jest@latest` v1.1.1
