### ISSUE TITLE
Cannot run JEST unit test on  “getRelatedListRecords” from uiRelatedListApi.

### ISSUE THREAD

**Issue by simon-nowak** [salesforce/sfdx-lwc-jest#278]
### Description

Hello here,

I’m working on a LWC component that use the  “[getRelatedListRecords](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.reference_wire_adapters_get_related_list_records)” from uiRelatedListApi. It’s working fine on my orgs. This UI API has been introduced with the salesforce v54.

My problem is about the JEST unit test. The error message is about the “getRelatedListRecords”. This module cannot be found.

I have the last version of  “@ salesforce/sfdx-lwc-jest”: “^1.1.0"
If I understand well this version is running the v53.

I took a look at the package documentation and found a reference to “prerelease”. But I don’t find any “prerelease” anywhere. And the “last” version is still the 1.1.0.

Does anyone know what are my solutions/workarounds here?

#### Steps to Reproduce

```js
// simplified test case
   it('shows error panel when wire return error', () => {
        const element = createElement('c-xxxx', {
            is: xxxx
        });
        document.body.appendChild(element);

        // Emit error from @wire
        getRelatedListRecords.error();

        return Promise.resolve().then(() => {
            const errorElement = element.shadowRoot.querySelector('c-error-panel');
            expect(errorElement).not.toBeNull();
        });
    });

```

```html
<!-- HTML for component under test -->
<template>  </template>
```

```js
// JS for component under test
import { LightningElement } from 'lwc';
import { getRelatedListRecords } from 'lightning/uiRelatedListApi';

export default class xxxx extends LightningElement {}

```

```bash
# Command to repro
sfdx-lwc-jest 
```

#### Expected Results
Runing the test.

Instead I have thoses errors (see more in screenshot)

error Invalid sourceApiVersion found in sfdx-project.json. Expected 53.0, found 55.0
Cannot find module 'lightning/uiRelatedListApi' from 'tradespeople-approval-acquisition/main/default/lwc/xxxx/xxxx.js'

### Version
-   @salesforce/sfdx-lwc-jest: 1.1.0
-   Node: 14.15.5

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/35262768/180222578-e9ad7b25-7145-44da-ba40-25587eeca014.png)

**Comment by p3v9d5ui** [comment]
Any resolution for this? This is blocking me as well.

**Comment by ekashida** [comment]
@Templarian looks like this stub is generated for core but not for platform.

**Comment by danielolaviobr** [comment]
@ekashida Are there any updates for this? I've updated to `1.1.2` and I'm still getting the same error

**Comment by karencvaleriano** [comment]
Hi, I'm also getting the same error. Is there already a fix on this? Thank you.

**Comment by p3v9d5ui** [comment]
I created a mock for this as: `force-app/test/jest-mocks/lightning/uiRelatedListApi.js`, which contains:

```
import { createLdsTestWireAdapter } from '@salesforce/wire-service-jest-util';

export const getRelatedListRecords = createLdsTestWireAdapter(jest.fn());
```

**Comment by karencvaleriano** [comment]
> I created a mock for this as: `force-app/test/jest-mocks/lightning/uiRelatedListApi.js`, which contains:
> 
> ```
> import { createLdsTestWireAdapter } from '@salesforce/wire-service-jest-util';
> 
> export const getRelatedListRecords = createLdsTestWireAdapter(jest.fn());
> ```

thanks @p3v9d5ui , it worked!!!
