### ISSUE TITLE
Missing winter23 tagged npm version 

### ISSUE THREAD

**Issue by alan-morey** [salesforce/sfdx-lwc-jest#294]
### Description

There is no `winter23` tagged version

https://www.npmjs.com/package/@salesforce/sfdx-lwc-jest

What is the appropriate version to use for Winter '23 environments?

README.md says:
> The npm `latest` tag corresponds to the latest version of this repo, not necessarily Salesforce production versions.

Is `latest` appropriate or not for Winter '23 now?

**Comment by alan-morey** [comment]
I tried upgrading depdency and then running `sfdx-lwc-jest` with follow versions:

- 1.1.3 [`latest`] - error Invalid sourceApiVersion found in sfdx-project.json. Expected 55.0, found 56.0
- 1.1.4 - error Invalid sourceApiVersion found in sfdx-project.json. Expected 55.0, found 56.0
- 1.2.1 [`prerelease`] - No errors, works as expected

I think the `latest` and `prerelease` tags on these versions are misleading.

**Comment by nolanlawson** [comment]
There is a winter23 branch; we just didn't submit the tag to npm apparently. https://github.com/salesforce/sfdx-lwc-jest/tree/winter23

**Comment by nolanlawson** [comment]
`prerelease` is wrong, I dunno what that tag is supposed to be for. `winter23` should be 1.2.1, so the fact that you didn't get any errors with that version is a good sign.

I've updated the `winter23` tag, and deleted the `prerelease` and `next` tags to make things less confusing. Thanks for opening this issue!

**Comment by alan-morey** [comment]
@nolanlawson Thanks for updating.

Just a few more notes:
  - [`README.md`](https://github.com/salesforce/sfdx-lwc-jest/blob/master/README.md) still mentions `prerelease` 2 times.
  - There is no git tag `v1.2.1`
