### ISSUE TITLE
How to configure jest to use mocks from node_modules from external 2gp dependencies

### ISSUE THREAD

**Issue by joeythomaschaske** [salesforce/sfdx-lwc-jest#305]
### Description
I am a package developer and have multiple 2gp packages contained in their own separate repos. These packages form dependencies.

If a package contains LWCs I would like to publish mocks via npm so that other managed packages that depend on it can  use them if they use the components from the package.

I am running into errors attempting to configure jest to use the mocks that are located in `node_modules` when the package is installed

Additionally, I have requested an example of how to do this correctly in the LWC Recipes [repo](https://github.com/trailheadapps/lwc-recipes/issues/784)

#### Steps to Reproduce
 - Create a package that contains an LWC
 - Create a corresponding mock component in `__mocks__`
 - publish the mock component to npm
- Create a separate package that is dependent on the first package
- Add the npm package from the first project to the project's dependencies and install it
- Configure `jest.config.js` via `moduleNameMapper` to use the mock from `node_modules`
- Run the jest tests

Example `jest.config.js`:
```js
const { jestConfig } = require('@salesforce/sfdx-lwc-jest/config');
module.exports = {
  ...jestConfig,
  roots: ['<rootDir>/force-app/main/default/lwc'],
  moduleNameMapper: {
    '^c/uiMessage$': '<rootDir>/node_modules/@komodohealth/p-pltfm-core/__mocks__/uiMessage.js',
  },
};
```

#### Expected Results

Jest uses the mock from `node_modules`

#### Actual Results

```bash
User@User tx-fnds-mvn-content % yarn test:lwc cmOfficeFileSelector
yarn run v1.22.19
$ ./node_modules/.bin/sfdx-lwc-jest -- cmOfficeFileSelector
error Invalid sourceApiVersion found in sfdx-project.json. Expected 57.0, found 56.0
 FAIL  force-app/main/default/lwc/cmOfficeFileSelector/__tests__/cmOfficeFileSelector.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/User/dev/Foundations/tx-fnds-mvn-content/node_modules/@komodohealth/p-pltfm-core/__mocks__/uiMessage.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { api, LightningElement } from 'lwc';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (force-app/main/default/lwc/cmOfficeFileSelector/cmOfficeFileSelector.html.compiled:8:1)
      at Object.<anonymous> (force-app/main/default/lwc/cmOfficeFileSelector/src/cmOfficeFileSelector.ts:2:31)
      at Object.<anonymous> (force-app/main/default/lwc/cmOfficeFileSelector/src/__tests__/cmOfficeFileSelector.test.ts:3:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.769 s
Ran all test suites matching /cmOfficeFileSelector/i.
```

### Version

-   @salesforce/sfdx-lwc-jest: 1.1.4
-   Node: 16.17.0

**Additional context/Screenshots**

`node_modules` content:

<img width="439" alt="Screenshot 2023-03-13 at 5 46 41 PM" src="https://user-images.githubusercontent.com/7061638/224849399-d5c115de-0ece-46a8-9172-6f63eb09c484.png">

`node_modules/@komodohealth/p-pltfm-core/__mocks__/uiMessage.js` contents:

```js
import { api, LightningElement } from 'lwc';
export default class UiMessage extends LightningElement {
  @api
  message;
  @api
  iconName = 'utility:info';
  @api
  iconVariant;
  @api
  iconSize = 'small';
}
```

**Comment by joeythomaschaske** [comment]
Ok I think I figured it out, in my `jest.config.js` I wasn't setting `transformIgnorePatterns` to ignore everything but my npm package with my mocks.

However, there's not a good way to add my npm packages to this with out also including what `sfdx-lwc-jest`  has in its base jest config

```json
transformIgnorePatterns: [
    '/node_modules/(?!(.*@salesforce/sfdx-lwc-jest/src/lightning-stubs)/)',
],
```

So I have to manually include this, which means if the source config changes it could cause problems

```json
transformIgnorePatterns: [
  '/node_modules/(?!(.*@salesforce/sfdx-lwc-jest/src/lightning-stubs|@komodohealth)/)'
],
```

**Comment by joeythomaschaske** [comment]
Additionally, someone on my team notified me about "Plug n Play" modules which is an entirely different format for storing external dependencies. They warned reaching into `node_modules` probably won't work with pnp modules.

`sfdx-lwc-jest` reaches into node_modules today, will this break using plug n play?

**Comment by nolanlawson** [comment]
This sounds like a question, so I think this issue can be closed. Please reopen if I'm mistaken.

I haven't tested plug n play personally, but in general, I would expect it to not be compatible with everything in the Node.js ecosystem, and there may be something in `sfdx-lwc-jest` that is incompatible, yes.
