### ISSUE TITLE
Add support for `jest.config.mjs` and `jest.config.cjs`

### ISSUE THREAD

**Issue by lukethacoder** [salesforce/sfdx-lwc-jest#313]
### Description

Currently `sfdx-lwc-jest` checks only for a `jest.config.js` file, but jest supports `jest.config.js|ts|mjs|cjs|json` ([reference](https://jestjs.io/docs/configuration)).

#### Steps to Reproduce

1. Create a `jest.config.cjs` file
2. Add your custom config (don't forget to extend the 
3. Run `sfdx-lwc-jest`
4. Custom jest config file is not picked up, no custom config is used

`jest.config.cjs`
```js
const { jestConfig } = require('@salesforce/sfdx-lwc-jest/config')

/** @type {import('jest').Config} */
const config = {
  ...jestConfig,
  modulePathIgnorePatterns: ['__docs__', '__example__'],
}

module.exports = config
```

or

`jest.config.mjs`
```js
import { jestConfig } from '@salesforce/sfdx-lwc-jest/config'

/** @type {import('jest').Config} */
const config = {
  ...jestConfig,
  modulePathIgnorePatterns: ['__docs__', '__example__'],
}

export default config
```

#### Expected Results

Allow `sfdx-lwc-jest` to use `.cjs` and `.mjs` jest config extensions.

#### Actual Results

`jest.config.cjs` and `jest.config.mjs` config files are ignored

### Version

-   @salesforce/sfdx-lwc-jest: 1.3.0
-   Node: 18.15.0

**Possible Solution**

Check for `.mjs` and `.cjs` jest config files here

https://github.com/salesforce/sfdx-lwc-jest/blob/bbdcfb1e5a5625108b9fb31550fad3f818ed4fc7/src/utils/test-runner.js#L62

```js
// Provide default configuration when none is present at the project root.
const hasCustomConfig = fs.existsSync(path.resolve(PROJECT_ROOT, 'jest.config.js'))
    || fs.existsSync(path.resolve(PROJECT_ROOT, 'jest.config.mjs'))
    || fs.existsSync(path.resolve(PROJECT_ROOT, 'jest.config.cjs'));
```

**Comment by nolanlawson** [comment]
Resolved by https://github.com/salesforce/sfdx-lwc-jest/pull/314
