### ISSUE TITLE
Peer dependencies issue when installing sfdx-lwc-jest v3.0.0

### ISSUE THREAD

**Issue by ogardnercertinia** [salesforce/sfdx-lwc-jest#336]
### Description

We install `sfdx-lwc-jest` using pnpm with the `strict-peer-dependencies` option set to true. When installing version 3.0.0 of `sfdx-lwc-jest`, we are greeted with the following error:

```bash
  └─┬ @salesforce/sfdx-lwc-jest 3.0.0
    ├─┬ @lwc/jest-preset 13.0.0
    │ ├── ✕ unmet peer @lwc/compiler@^2.48.0: found 3.1.3 in @salesforce/sfdx-lwc-jest
    │ ├── ✕ unmet peer @lwc/engine-dom@^2.48.0: found 3.1.3 in @salesforce/sfdx-lwc-jest
    │ ├── ✕ unmet peer @lwc/engine-server@^2.48.0: found 3.1.3 in @salesforce/sfdx-lwc-jest
    │ ├── ✕ unmet peer @lwc/synthetic-shadow@^2.48.0: found 3.1.3 in @salesforce/sfdx-lwc-jest
    │ └─┬ @lwc/jest-transformer 13.0.0
    │   └── ✕ unmet peer @lwc/compiler@^2.48.0: found 3.1.3 in @salesforce/sfdx-lwc-jest
    └─┬ @salesforce/wire-service-jest-util 4.0.1
      └── ✕ unmet peer @lwc/engine-dom@^2.0.0: found 3.1.3 in @salesforce/sfdx-lwc-jest
```

#### Steps to Reproduce

Install `sfdx-lwc-jest` version 3.0.0 via pnpm with the `strict-peer-dependencies` option set to true.

#### Expected Results

`sfdx-lwc-jest` dependency is installed correctly.

#### Actual Results

Error is thrown. See above.

### Version

-   @salesforce/sfdx-lwc-jest: 3.0.0
-   Node: 18.15.0

**Possible Solution**

It seems that the peer dependency issue was fixed in version 14 of `@lwc/jest-preset` / `@lwc/jest-transformer`, and version 4.0.2 of `@salesforce/wire-service-jest-util`. We should upgrade `sfdx-lwc-jest`'s dependencies to match.

**Additional context/Screenshots**

N/A

**Comment by ogardnercertinia** [comment]
I just cloned this repo and ran `yarn install` and there are errors in my terminal:

```bash
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @lwc/jest-preset@13.0.0" has incorrect peer dependency "@lwc/compiler@^2.48.0".
warning " > @lwc/jest-preset@13.0.0" has incorrect peer dependency "@lwc/engine-dom@^2.48.0".
warning " > @lwc/jest-preset@13.0.0" has incorrect peer dependency "@lwc/engine-server@^2.48.0".
warning " > @lwc/jest-preset@13.0.0" has incorrect peer dependency "@lwc/synthetic-shadow@^2.48.0".
warning " > @lwc/jest-transformer@13.0.0" has incorrect peer dependency "@lwc/compiler@^2.48.0".
warning " > @salesforce/wire-service-jest-util@4.0.1" has incorrect peer dependency "@lwc/engine-dom@^2.0.0".
[4/4] 🔨  Building fresh packages...
```

**Comment by nolanlawson** [comment]
Updating deps fixes it ^

**Comment by ogardnercertinia** [comment]
Hey @nolanlawson, thanks for merging a fix for this!
Do you know when we can expect a patch of `sfdx-lwc-jest` to be released?
This issue is currently blocking us from adopting version 3.
Thanks!

**Comment by jmsjtu** [comment]
@ogardnercertinia I'll do a release today.

**Comment by jmsjtu** [comment]
@ogardnercertinia release is out now.
