### ISSUE TITLE
Missing spring24 tagged release

### ISSUE THREAD

**Issue by alan-morey** [salesforce/sfdx-lwc-jest#347]
### Description
Trying to upgrade my project dependencies for the Spring '24 release and noticed there is no `spring24` tagged release on npmjs.com

https://www.npmjs.com/package/@salesforce/sfdx-lwc-jest?activeTab=versions

1. What is the recommended version for Spring '24?
2. Will there be a `spring24` tagged version release?

**Comment by nolanlawson** [comment]
Sorry for missing that. The `spring24` npm tag is now published using [v3.1.2](https://github.com/salesforce/sfdx-lwc-jest/releases/tag/v3.1.2). For more details on LWC versions vs Salesforce versions, please see: https://lwc.dev/guide/versioning
