### ISSUE TITLE
LWC errors appears in test results for lightning namespace components

### ISSUE THREAD

**Issue by marktuk** [salesforce/sfdx-lwc-jest#57]
When I run the tests for this very simple component:
https://gist.github.com/marktuk/aef0f424f4b3b2f52440a870314eb203

I get these errors in the output:
```
> lwc-jest

 PASS  force-app/main/default/lwc/testCard/__tests__/testCard.test.js
  c-test-card
    ✓ generates LWC errors? (263ms)

  console.error node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:192
    [LWC error]: Invalid operation on Element [object:vm undefined (0)]. Elements created via a template should not be mutated us
ing DOM APIs. Instead of attempting to update this element directly to change the value of attribute "title", you can update the state of the component, and let the engine to rehydrate the element accordingly.
    <lightning-card>

  console.error node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:192
    [LWC error]: Invalid attribute "title" for [object:vm undefined (0)]. Instead access the public property with `element.title;`.
    <lightning-card>

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        4.958s
Ran all test suites.
```

From what I can tell, they are possibly things that need addressing in the implementation of `<lightning-card>`? In which case, should we even be seeing errors generated by components outside of our namespace?

EDIT: We see these for every instance of `<lightning-card>`, so as you can imagine in a more complex component the errors stack up and make it look like the tests have got lots of issues.

**Comment by trevor-bliss** [comment]
Yeah we should add back the `title` prop to the lightning-card stub. We moved to a new script to generate the stubs and it mistakenly excluded global HTML attributes.
