### ISSUE TITLE
Move all links and packages from lwc-jest => sfdx-lwc-jest

### ISSUE THREAD

**Issue by diervo** [salesforce/sfdx-lwc-jest#62]
Right now lwc-jest repo is a redirect to sfdx-lwc-jest.
We need to:
- Change in the docs all ocurrences of lwc-jest to sfdx-lwc-jest
- Decide wether lwc-test is just a redirect as now, or we want a readme explaining the migration.

**Comment by trevor-bliss** [comment]
I'm working on this now. Plan is as follows:

- [x] Create branch named `lwc-jest` based on current `master`
- [ ] Add deprecation notice to `lwc-jest` branch README
- [ ] Rename npm package and references to `@salesforce/sfdx-lwc-jest` on `master`, release to NPM
- [ ] Update all projects we own (lwc-recipes, etc)
- [ ] Keep `lwc-jest` and `sfdx-lwc-jest` versions in sync, publish npm to both for all of Winter20 to give customers a chance to update their projects
- [ ] Update SFDC Release notes to mention name change
- [ ] In Spring20, kill the `lwc-jest` branch and stop updating NPM, continue all development and releases against `@salesforce/sfdx/lwc-jest`

**Comment by trevor-bliss** [comment]
Just waiting for usage numbers of `lwc-jest` to drop enough to be able to stop updating that package. Just waiting on the go ahead from @Gr8Gatsby. No need to keep this Issue open.
