### ISSUE TITLE
Unable to test component if it uses third party components

### ISSUE THREAD

**Issue by angelsalazar** [salesforce/sfdx-lwc-jest#67]
Hello, I have run into a situation where I am not able to test a component because it is using a  third party component as part of its internal implementation.

is there a way to test this scenario?

**Comment by pmdartus** [comment]
I am not clear about what you are asking. Can you give a concrete example of what you are trying to achieve?

**Comment by angelsalazar** [comment]
Sorry about that.
Considering the following scenario where you have a DCP containing resuable components (cmp-a, cmp-b, and cmp-c)

**Comment by muenzpraeger** [comment]
In that case you would have to mock `cmp-a` and `cmp-c`.

**Comment by trevor-bliss** [comment]
@angelsalazar You can override the default Jest configs `moduleNameMapper` entry to map the inaccessible components to your own stubs. See the following section of the README for an example:

https://github.com/salesforce/sfdx-lwc-jest#resolving-external-lightning-web-components

**Comment by angelsalazar** [comment]
make sense,
