### ISSUE TITLE
Upgrade @lwc/jest-transformer to remove deasync

### ISSUE THREAD

**Issue by dehru** [salesforce/sfdx-lwc-jest#70]
Hello, I'm wondering when you're going to upgrade these lwc dependencies from "0.37.4-220.2".  We are hoping to get rid of deasync and it looks like that was removed in this PR https://github.com/salesforce/lwc/pull/1174 and published around 0.38.1.

**Comment by trevor-bliss** [comment]
The LWC dependencies this project consumes are dependent on what is currently released to Salesforce production. Currently, that's still version `0.37.4-220.2`.

However, as of version `0.5.1` for this project the `deasync` dependency has been removed. The commit that removes the dependency is [here](https://github.com/salesforce/sfdx-lwc-jest/commit/421f3442e79facb7db85f3f7c3f078fe196600fc). 

Let me know if you still `deasync` issues after upgrading to 0.5.1 and I can reopen this.
