### ISSUE TITLE
Code Coverage option is returning all coverage percents as 0

### ISSUE THREAD

**Issue by tprince232** [salesforce/sfdx-lwc-jest#71]
When I run `npm run test:unit:coverage`, I get a coverage percent of 0 for Statements, Branches, Functions and Lines and no data in the index.html in the coverage/lcov-report folder.

This issue is occurring in the repository I am developing in, so I tested out a fresh clone of lwc-recipes, running npm install, and running the unit tests with code coverage, and the same issue is occurring in my lwc-recipies folder.

This error is also appearing throughout the tests:

```
PASS  force-app/main/default/lwc/compositionWithAppBuilder/__tests__/compositionWithAppBuilder.test.js
  ● Console

    console.error node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:199
      [LWC error]: Invalid operation on Element [object:vm undefined (2)]. Elements created via a template should not be mutated using DOM APIs. Instead of attempting to update this element directly to change the value of attribute "title", you can update the state of the component, and let the engine to rehydrate the element accordingly.
      <lightning-card>
    console.error node_modules/@lwc/engine/dist/commonjs/es2017/engine.js:199
      [LWC error]: Invalid attribute "title" for [object:vm undefined (2)]. Instead access the public property with `element.title;`.
      <lightning-card>
```

Please let me know if I am missing something or if this is something Salesforce will need to address.

**Comment by tprince232** [comment]
Note that I am using a Windows 10 machine and my Node version is v10.16.0. Are there any other variables to consider?

**Comment by trevor-bliss** [comment]
I can confirm for the lwc-recipes project, code coverage functions as expected on Mac, but reports 0% on Windows.

Interestingly, if I add the `collectCoverageFrom` option to the Jest config the numbers are reported. @tprince232 could you add the following to your local Jest config (for lwc-recipes that's the jest.config.js file in the project root) and run with the `--coverage` flag agin?:
```
collectCoverageFrom: [
       "force-app/main/default/lwc/**/*.js",
	"!**/node_modules/**"
]
```

**Comment by tprince232** [comment]
Hi @trevor-bliss, I added the `collectCoverageFrom` and the coverage numbers & report files were generated as expected. Thanks!

**Comment by rtm** [comment]
THe OP also wondered about this error:

```
[LWC error]: Invalid attribute "title" for [object:vm undefined (2)]. Instead access the public property with `element.title;`.
      <lightning-card>
```

I'm getting this too. Is this some kind of conflict with the built-in `title` attribute? Happens only during tests. Any workaround?
