### ISSUE TITLE
Test runner performance improvement

### ISSUE THREAD

**Issue by pmdartus** [salesforce/sfdx-lwc-jest#75]
## Observation

When running `@salesforce/lwc-jest` against the [receipes](https://github.com/trailheadapps/lwc-recipes) repo in debug mode we can observe that more than half the time during the test run is spent resolving modules. Here is the observed recorded [trace.zip](https://github.com/salesforce/sfdx-lwc-jest/files/3391432/lwc-jest-receipes.zip)

It takes in total 42 seconds to run the tests suite against the receipes repo when running in tests sequentially. When looking at the trace we can observe 2 stops where we spent time resolving LWC modules:
* When the test runner boot up (4.89 sec. / ~10% of the total test run time). https://github.com/salesforce/sfdx-lwc-jest/blob/fbd7c430d5d20ed1e98a0b3899b2234b8364cc46/src/resolver.js#L83
* When jest attempt to resolve a module (22.07 sec. / ~53% of the total test run time): https://github.com/salesforce/sfdx-lwc-jest/blob/fbd7c430d5d20ed1e98a0b3899b2234b8364cc46/src/utils/project.js#L37

We can also notice that the error logging represents around 10% of the total test run time. 

## Steps to reproduce

* `$ npm run test:unit -- --coverage --debug`
* Attach debugger
* Run with pofiler attached

## Environment

* Node: `v10.16.0`
* npm: `v6.9.0`
* @salesforce/lwc-jest: `v0.5.1`

**Comment by trevor-bliss** [comment]
Related change to speed up the LWC resolver: https://github.com/salesforce/lwc/pull/1414
