### ISSUE TITLE
Stub of lightning-emp-api is missing

### ISSUE THREAD

**Issue by shunkosa** [salesforce/sfdx-lwc-jest#87]
### Description
Stub of [lightning-emp-api](https://developer.salesforce.com/docs/component-library/bundle/lightning-emp-api/documentation) is missing in [lightning-stubs](https://github.com/salesforce/sfdx-lwc-jest/tree/master/src/lightning-stubs) directory. Is it intended?

**Comment by trevor-bliss** [comment]
That is not intended. Looks like that component is on the newer side and just slipped through the cracks. Thanks for pointing that out.
