### ISSUE TITLE
lightning-input stub missing attributes

### ISSUE THREAD

**Issue by NTaylor1993** [salesforce/sfdx-lwc-jest#93]
The stub for lightning-input is missing date-style, and time-style attributes.

These were added in the Summer 19 update as per the release notes https://releasenotes.docs.salesforce.com/en-us/summer19/release-notes/rn_lwc_components.htm

**Comment by trevor-bliss** [comment]
Fixed by https://github.com/salesforce/sfdx-lwc-jest/pull/94
