### ISSUE TITLE
LWC Warnings from toast and lightning stubs

### ISSUE THREAD

**Issue by wollamshram** [salesforce/sfdx-lwc-jest#95]
### Description
Have encountered two scenarios in which testing code just as the Salesforce documentation suggests causes warnings from LWC.

One is when using CreateToastEvent. The warning raised is "Invalid event type "lightning__showtoast" dispatched in element <c-my-component>. Event name should only contain lowercase alphanumeric characters."

The other is when manually setting the value of a standard lightning component (e.g. a lightning-input. Also happens with lightning-radio-group and presumably others). The warning raised is "If property value decorated with @api in [object:vm undefined (2)] is used in the template, the value val set manually may be overridden by the template, consider binding the property only in the template."

#### Steps to Reproduce
JS:
```
import {ShowToastEvent} from 'lightning/platformShowToastEvent';

export default class MyComponent extends LightningElement {

    handleButtonClick() {
	this.dispatchEvent(new ShowToastEvent({
	    title: 'title',
	    message: 'message',
	    variant: 'error',
   	    mode: 'sticky'
	}));
    }
}
```

HTML:
```
<template>
    <lightning-button>
        label="label"
        onclick={handleButtonClick}
    </lightning-button>

    <lightning-input>
        label="label"
    </lightning-input>
</template>
```

Test:
```
test('test', () => {
    let componentUnderTest = createElement('c-my-component', {
        is: MyComponent,
    });
    document.body.appendChild(componentUnderTest);

    return Promise.resolve().then(() => {
        const input= componentUnderTest.shadowRoot.querySelector('lightning-input');
	input.value = 'val';
	input.dispatchEvent(new CustomEvent('change'));

        const button= componentUnderTest.shadowRoot.querySelector('lightning-button');
        button.click();
    }):
});
```

```bash
# Command to repro
lwc-jest
```

#### Expected Results
No warnings are raised.

#### Actual Results
Both warnings mentioned above are raised.

### Version
- @salesforce/lwc-jest: 0.5.4
- Node: 12.11.0

**Comment by ekashida** [comment]
@wollamshram Thanks for raising these concerns. The event name restriction was updated to start with a lowercase letter and only contain lowercase letters, numbers, and underscore:
https://github.com/salesforce/lwc/commit/371368616064cd4ff5d1651230c5f3b0558fe8dd

The other error has been removed.

I'm not sure which environment you're seeing those in, but they should eventually disappear as they make their way into production.
